### ISSUE TITLE
[BUG] Link in description displays a blank page

### ISSUE THREAD

**Issue by Snailedlt** [lunatic-fox/deviconapi#6]
http://deviconapi.vercel.app/
![image](https://user-images.githubusercontent.com/43886029/223400106-2b5edae9-b0dd-452b-bf8e-6c6471365238.png)

I assume we want to update it to this link: https://lunaticfox.vercel.app/deviconApi

**Comment by lunatic-fox** [comment]
Thank you for this great feedback! 🤩🚀
